// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AccountLink struct {
	ID              int64     `json:"id"`
	DiscordMemberID int64     `json:"discord_member_id"`
	RunescapeName   string    `json:"runescape_name"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type GuildConfig struct {
	ID                int64         `json:"id"`
	GuildID           int64         `json:"guild_id"`
	CoordinatorRoleID sql.NullInt64 `json:"coordinator_role_id"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type GuildWarningChannel struct {
	ID        int64     `json:"id"`
	GuildID   int64     `json:"guild_id"`
	ChannelID int64     `json:"channel_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SchedulableEvent struct {
	ID             int64     `json:"id"`
	Type           string    `json:"type"`
	Activity       string    `json:"activity"`
	Location       string    `json:"location"`
	ScheduledAt    time.Time `json:"scheduled_at"`
	CreatedAt      time.Time `json:"created_at"`
	DiscordEventID string    `json:"discord_event_id"`
}

type SchedulableEventParticipation struct {
	ID            int64     `json:"id"`
	EventID       int64     `json:"event_id"`
	AccountLinkID int64     `json:"account_link_id"`
	Notified      bool      `json:"notified"`
	CreatedAt     time.Time `json:"created_at"`
}

type TrackableEvent struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	Activity  string    `json:"activity"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type TrackableEventParticipation struct {
	ID            int64         `json:"id"`
	EventID       int64         `json:"event_id"`
	AccountLinkID int64         `json:"account_link_id"`
	StartingPoint int64         `json:"starting_point"`
	EndPoint      sql.NullInt64 `json:"end_point"`
	CreatedAt     time.Time     `json:"created_at"`
}

type TrackableEventProgress struct {
	ID              int64     `json:"id"`
	ParticipationID int64     `json:"participation_id"`
	Progress        int64     `json:"progress"`
	FetchedAt       time.Time `json:"fetched_at"`
}

type Warning struct {
	ID          int64     `json:"id"`
	GuildID     int64     `json:"guild_id"`
	UserID      int64     `json:"user_id"`
	ModeratorID int64     `json:"moderator_id"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
}

type WomCompetition struct {
	ID               int64     `json:"id"`
	WomCompetitionID int64     `json:"wom_competition_id"`
	VerificationCode string    `json:"verification_code"`
	DiscordThreadID  string    `json:"discord_thread_id"`
	Metric           string    `json:"metric"`
	Type             string    `json:"type"`
	CreatedAt        time.Time `json:"created_at"`
}
