// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"time"
)

type Querier interface {
	ActivateAccountLink(ctx context.Context, id int64) error
	CreateAccountLink(ctx context.Context, arg CreateAccountLinkParams) (AccountLink, error)
	CreateGuildConfig(ctx context.Context, arg CreateGuildConfigParams) (GuildConfig, error)
	CreateSchedulableEvent(ctx context.Context, arg CreateSchedulableEventParams) (SchedulableEvent, error)
	CreateSchedulableParticipation(ctx context.Context, arg CreateSchedulableParticipationParams) (SchedulableEventParticipation, error)
	CreateTrackableEvent(ctx context.Context, arg CreateTrackableEventParams) (TrackableEvent, error)
	CreateTrackableParticipation(ctx context.Context, arg CreateTrackableParticipationParams) (TrackableEventParticipation, error)
	CreateTrackableProgress(ctx context.Context, arg CreateTrackableProgressParams) error
	CreateUserTimezone(ctx context.Context, arg CreateUserTimezoneParams) (UserTimezonePreference, error)
	CreateWOMCompetition(ctx context.Context, arg CreateWOMCompetitionParams) (WomCompetition, error)
	CreateWarning(ctx context.Context, arg CreateWarningParams) (Warning, error)
	DeactivateAccountLink(ctx context.Context, id int64) error
	DeactivateAllAccountLinksForUser(ctx context.Context, discordMemberID int64) error
	DeactivateTrackableEvent(ctx context.Context, id int64) error
	DeleteGuildWarningChannel(ctx context.Context, guildID int64) error
	DeleteSchedulableEvent(ctx context.Context, id int64) error
	DeleteUserTimezone(ctx context.Context, discordUserID int64) error
	DeleteWOMCompetition(ctx context.Context, id int64) error
	GetAccountLinkByDiscordID(ctx context.Context, discordMemberID int64) (AccountLink, error)
	GetAccountLinkByID(ctx context.Context, id int64) (AccountLink, error)
	GetAccountLinkByUsername(ctx context.Context, runescapeName string) (AccountLink, error)
	GetActiveTrackableEvents(ctx context.Context) ([]TrackableEvent, error)
	GetActiveTrackableEventsByType(ctx context.Context, type_ string) ([]TrackableEvent, error)
	GetAllAccountLinksForUser(ctx context.Context, discordMemberID int64) ([]AccountLink, error)
	GetAllEventWinnersByType(ctx context.Context, type_ string) ([]GetAllEventWinnersByTypeRow, error)
	GetEventWinners(ctx context.Context, eventID int64) ([]GetEventWinnersRow, error)
	GetExistingAccountLink(ctx context.Context, arg GetExistingAccountLinkParams) (AccountLink, error)
	GetGuildConfig(ctx context.Context, guildID int64) (GuildConfig, error)
	GetGuildWarningChannel(ctx context.Context, guildID int64) (GuildWarningChannel, error)
	GetLastActiveEventByType(ctx context.Context, type_ string) (TrackableEvent, error)
	GetLatestWOMCompetitionByType(ctx context.Context, type_ string) (WomCompetition, error)
	GetProgressForParticipation(ctx context.Context, participationID int64) ([]TrackableEventProgress, error)
	GetSchedulableEventByID(ctx context.Context, id int64) (SchedulableEvent, error)
	GetSchedulableEvents(ctx context.Context) ([]SchedulableEvent, error)
	GetSchedulableEventsInTimeRange(ctx context.Context, arg GetSchedulableEventsInTimeRangeParams) ([]SchedulableEvent, error)
	GetSchedulableParticipation(ctx context.Context, arg GetSchedulableParticipationParams) (SchedulableEventParticipation, error)
	GetSchedulableParticipationsByEvent(ctx context.Context, eventID int64) ([]GetSchedulableParticipationsByEventRow, error)
	GetTrackableEventByID(ctx context.Context, id int64) (TrackableEvent, error)
	GetTrackableParticipation(ctx context.Context, arg GetTrackableParticipationParams) (TrackableEventParticipation, error)
	GetTrackableParticipationsByEvent(ctx context.Context, eventID int64) ([]GetTrackableParticipationsByEventRow, error)
	GetUnnotifiedParticipations(ctx context.Context, arg GetUnnotifiedParticipationsParams) ([]GetUnnotifiedParticipationsRow, error)
	GetUpcomingSchedulableEvents(ctx context.Context, scheduledAt time.Time) ([]SchedulableEvent, error)
	GetUserTimezone(ctx context.Context, discordUserID int64) (UserTimezonePreference, error)
	GetWOMCompetitionByID(ctx context.Context, id int64) (WomCompetition, error)
	GetWOMCompetitionByThreadID(ctx context.Context, discordThreadID string) (WomCompetition, error)
	GetWOMCompetitionByWOMID(ctx context.Context, womCompetitionID int64) (WomCompetition, error)
	GetWOMCompetitionsByType(ctx context.Context, type_ string) ([]WomCompetition, error)
	GetWarningByID(ctx context.Context, id int64) (Warning, error)
	GetWarningsByGuild(ctx context.Context, guildID int64) ([]Warning, error)
	GetWarningsByUser(ctx context.Context, arg GetWarningsByUserParams) ([]Warning, error)
	MarkParticipationAsNotified(ctx context.Context, id int64) error
	SetGuildWarningChannel(ctx context.Context, arg SetGuildWarningChannelParams) (GuildWarningChannel, error)
	UpdateCompetitionCodeChannel(ctx context.Context, arg UpdateCompetitionCodeChannelParams) error
	UpdateCoordinatorRole(ctx context.Context, arg UpdateCoordinatorRoleParams) error
	UpdateDefaultTimezone(ctx context.Context, arg UpdateDefaultTimezoneParams) error
	UpdateEventNotificationChannel(ctx context.Context, arg UpdateEventNotificationChannelParams) error
	UpdateEventNotificationRole(ctx context.Context, arg UpdateEventNotificationRoleParams) error
	UpdateTrackableParticipationEndPoint(ctx context.Context, arg UpdateTrackableParticipationEndPointParams) error
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) error
	UpsertGuildConfig(ctx context.Context, arg UpsertGuildConfigParams) error
	UpsertUserTimezone(ctx context.Context, arg UpsertUserTimezoneParams) error
}

var _ Querier = (*Queries)(nil)
