version: 2

linters:
  disable:
    - errcheck  # Too noisy, especially for Discord interaction responses that log internally
    - staticcheck  # Disable style suggestions

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec

    # Exclude known linters from partially hard-vendored code (sqlc generated)
    - path: internal/database/
      linters:
        - all

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

run:
  timeout: 5m
